language: ruby
install:
  - gem install bundler
  - bundle
  - bundle exec rake compile
rvm:
  - 2.3.1
  - 2.2
  - 2.1
script:
  - CODECLIMATE_REPO_TOKEN=1f8b081f3fcd3df43233f07c77d0830fdccca614a1efc1a6ec5485a59e24625c bundle exec rake spec
